# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test IP Pool
#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: create IP Pool
      nsxt_policy_ip_pool:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: "{{validate_certs}}"
        display_name: "{{item.display_name}}"
        state: "{{state}}"
        pool_static_subnets:
           - display_name: "{{item.display_name}}"
             state: "{{state}}"
             allocation_ranges: "{{item.allocation_ranges}}"
             cidr: "{{item.cidr}}"
      with_items:
        - "{{ip_pools}}"