# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
   - vars/edge_info_vars.yml
  tasks:
    - name: Create edge transport nodes
      nsxt_transport_nodes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: "{{validate_certs}}"
        display_name: "{{item.display_name}}"
        description: "{{item.description}}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        node_deployment_info: "{{item.node_deployment_info}}"
        state: "{{state}}"
      with_items:
        - "{{transport_nodes}}"

    - name: List fabric nodes
      nsxt_transport_nodes_facts:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
      check_mode: yes